name: capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - beautifulsoup4=4.8.2
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cftime=1.1.1.1
  - chardet=3.0.4
  - colorama=0.4.3
  - cryptography=2.9.2
  - curl=7.69.1
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - eccodes=2.17.0
  - entrypoints=0.3
  - freetype=2.9.1
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.9
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.2
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.0.1
  - krb5=1.17.1
  - libcurl=7.69.1
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.9.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - netcdf4=1.5.3
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pickleshare=0.7.5
  - pip=20.0.2
  - proj=7.0.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - pycparser=2.20
  - pygments=2.6.1
  - pygrib=2.0.4
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyproj=2.6.0
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2019.3
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.2
  - qtpy=1.9.0
  - requests=2.23.0
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.1.3
  - sip=4.19.13
  - six=1.14.0
  - soupsieve=2.0.1
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - nose==1.3.7

